> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions. 

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

<IPython.core.display.Javascript object>

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "abhijeet-chatterjee2019/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations


'https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
#function1 = np.eye(n) 
#function2 = arr.T
#function3 = arr.flatten()
#function4 = np.var(arr)
#function5 = np.std(arr,axis)

NameError: name 'n' is not defined

## Function 1 - np.eye(N) (change this)
This function helps to generate a NxN identity square matrix 
[1 0 0]
[0 1 0]
[0 0 1]
Identity Matrix of 3 by 3
Identity matrix is the one in which all the diagonal elememts are one 1 and rest are 0.

In [6]:
# Example 1 - working (change this)
IdentityMat3=np.eye(3)
print(IdentityMat3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


This generates an identity matrix of 3X3 and stores in the variable IdentityMat3.

In [7]:
# Example 2 - working
IdentityMat6=np.eye(6)
print(IdentityMat6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Now the identity matrix of 6X6 will be generated and stored in the variable.

In [8]:
# Example 3 - breaking (to illustrate when it breaks)
IdentityMatbreak=np.eye(-1)

ValueError: negative dimensions are not allowed

This Function generates an error if negative values are passed to it as parameter because a matrix never has negative rows or columns. This function only takes parameters more than 0 and it also takes only integer values as parameter.

This function is used when you require an identity matrix for the matrix calculation.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "abhijeet-chatterjee2019/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations


'https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations'

## Function 2 - arr.T

arr.T function gives the transpose of the matrix given in arr variable

In [10]:
# Example 1 - working
arr=np.array([(1,2,3),(4,5,6)])
print(arr)
print("Transposed Matrix is:")
print(arr.T)

[[1 2 3]
 [4 5 6]]
Transposed Matrix is:
[[1 4]
 [2 5]
 [3 6]]


The values of rows have become the values of columns and the values of column have become the values of the rows.

In [11]:
# Example 2 - working
arr=np.array([('a','b','c'),('d','e','f'),('g','h','i')])
print(arr)
print("After Transposing:")
print(arr.T)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]
After Transposing:
[['a' 'd' 'g']
 ['b' 'e' 'h']
 ['c' 'f' 'i']]


This function works on all matrices irrespective of datatype and transposes the values.

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr=np.array([1,2,3])
print(arr)
print("Transposed:")
print(arr.T)

[1 2 3]
Transposed:
[1 2 3]


As you can see above if instead of matrix a 1D array is given it does not transposes the values in columns.It only works on 2D arrays.

Some closing comments about when to use this function.

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "abhijeet-chatterjee2019/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations


'https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations'

## Function 3 - arr.flatten()

This function splits the bigger array into smaller equal arrays.

In [14]:
# Example 1 - working
arr=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr)
print("Splitted")
print(np.split(arr,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Splitted
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


This function takes array and splits them into the number of smaller arrays of equal number of elements

In [15]:
# Example 2 - working
arr=np.array([('a','b'),('d','c'),('e','f'),('h','g')])
print(arr)
print("splitting array")
splitted=np.split(arr,2)
print(splitted)

[['a' 'b']
 ['d' 'c']
 ['e' 'f']
 ['h' 'g']]
splitting array
[array([['a', 'b'],
       ['d', 'c']], dtype='<U1'), array([['e', 'f'],
       ['h', 'g']], dtype='<U1')]


Here the array has been splitted into two sets of 2 elements and 2 elements

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
arr=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr)
print("Splitted")
print(np.split(arr,2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Splitted


ValueError: array split does not result in an equal division

This function breaks if the number of elements in the array is not completely divisible by the number of partitions tot be made. This can be corrected if we put if check before using this function.

This function is used to make smalle parts of the array so that can work on them seprtely without disturbing the actual array.

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "abhijeet-chatterjee2019/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations


'https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations'

## Function 4 - np.count_nonzero(arr)

This function counts the no. of non zero elements in an array arr.

numpy.count_nonzero(a, axis=None, *, keepdims=False)

In [18]:
# Example 1 - working
arr=np.array([(1,2,3)])
print(arr)
print("Number of non zero Elements:")
print(np.count_nonzero(arr))

[[1 2 3]]
Number of non zero Elements:
3


This function provide the number of non-zero elements present in the array.

In [19]:
# Example 2 - working
arr=np.array([(0,2,3),(4,0,6),(0,0,0)])
print(arr)
print("Number of non-zero elements:")
print(np.count_nonzero(arr))

[[0 2 3]
 [4 0 6]
 [0 0 0]]
Number of non-zero elements:
4


This function is takes all the array elements and and counts all the numbers that are nonzero.

In [20]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.array()
print(np.count_nonzero(arr))

TypeError: array() missing required argument 'object' (pos 1)

This function atleast needs one element in the array to to work.

You can easily find the number elements which are zero and non-zero in the given unknown matrix

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "abhijeet-chatterjee2019/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations


'https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations'

## Function 5 - np.std(arr,axis)

This function is used to calculate standard deviation across an axis.

In [22]:
# Example 1 - working
arr=np.array([1,2,3])
print(arr)
print("Standard Deviation:",np.std(arr,0))

[1 2 3]
Standard Deviation: 0.816496580927726


This function calculate the standard deviation of the elements along the given axis.

In [23]:
# Example 2 - working
arr=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr)
print("Standard Deviation:",np.std(arr,1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Standard Deviation: [0.81649658 0.81649658 0.81649658]


In this example, as the axis is given 1 so the stndrd deviation in columns are given stored in an 1D array

In [24]:
# Example 3 - breaking (to illustrate when it breaks)
arr=np.array([(1,2,3),(4,5,6),(7,8,9)])
print(arr)
print("Standard Deviation:",np.std(arr,2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


IndexError: tuple index out of range

This function breaks if you provide axis that dos not exist as 2 means 3rd dimension but the array is 2D

This function is used to calculate the standard deviation of the rows of the given axis and savs it in array format. 

In [25]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "abhijeet-chatterjee2019/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations


'https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations'

## Function  6- arr.resize((m,n))

Used to resize a array to different dimension(ie change the number of rows and columns of an array).

In [26]:
# Example 1 - working
arr=np.array([(1,2,3),(4,5,6)])
print(arr)
print("Resizing to 3 rows and 3 columns")
print(np.resize(arr,(3,3)))

[[1 2 3]
 [4 5 6]]
Resizing to 3 rows and 3 columns
[[1 2 3]
 [4 5 6]
 [1 2 3]]


This function resizes the array provided and uses its alements to create a new array

In [27]:
# Example 2 - working
arr=np.array([(1,2),(4,5),(6,7),(8,9)])
print(arr)
print("Resizing to 3 rows and 4 columns")
print(np.resize(arr,(3,4)))

[[1 2]
 [4 5]
 [6 7]
 [8 9]]
Resizing to 3 rows and 4 columns
[[1 2 4 5]
 [6 7 8 9]
 [1 2 4 5]]


It combines various rows and columns to form the array of required rows and column

In [29]:
# Example 3 - breaking (to illustrate when it breaks)
arr=np.array([(1,2,3),(4,5,6)])
print(arr)
print("Resizing to -1 rows and -1 columns")
print(np.resize(arr,(-1,-1)))

[[1 2 3]
 [4 5 6]]
Resizing to -1 rows and -1 columns


ValueError: can only specify one unknown dimension

This functon Breaks beacuse the prameter that are passed are negative and it cannot be resizes to negative rows and columns.
Can be solved if used the absolute value of the parameter provided.

This function is used to resize an existing array to desired size eg. to be used in matrix multiplication

In [30]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "abhijeet-chatterjee2019/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations


'https://jovian.ml/abhijeet-chatterjee2019/numpy-array-operations'

## Conclusion

So,these are some among the huge list of numpy functions listed here along with their 2 working situations and also one condition where the function causes runtime error along with explanation so can avoid those situations.

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* For extra references--                                                                                                       
https://www.dataquest.io/blog/numpy-cheat-sheet/                                                                               
http://geeksforgeeks.org/

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
